version: '3'

services:
  app:
    image: bryan954781/docker-dotnet:0.0.2
    ports:
      - 5000:8080
    container_name: dotnet-asp
    depends_on:
      - db


  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dotnet-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    restart: always